import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import SignIn from '@/components/SignIn'
import SignUp from '@/components/SignUp'
import { useState } from 'react'

export default function Home() {
  const [showLogin, setShowLogin] = useState(true)
  const changeView = () => {
    setShowLogin(!showLogin)
  }
  return (
    <>
      <Head>
        <title>Board.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className = {styles.side_bar}>
          <span>Board.</span>
        </div>
        <div className={styles.container}>
          {showLogin?<SignIn changeView={changeView}/>:<SignUp changeView={changeView}/>}
        </div>
      </main>
    </>
  )
}
